/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: DevPoly3D (https://sketchfab.com/DevPoly3D)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/neovector-x-01-futuristic-sci-fi-design-c74c794552d242d8ac56da4dfcaa6fc9
Title: NeoVector X-01 | Futuristic Sci-Fi Design
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/neovector_x-01__futuristic_sci-fi_design/scene.gltf')
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <group position={[0, 140.291, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube_Dark_0.geometry}
            material={materials.Dark}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube_White_0.geometry}
            material={materials.White}
          />
        </group>
        <group position={[0, 140.291, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube007_Dark_0.geometry}
            material={materials.Dark}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube007_White_0.geometry}
            material={materials.White}
          />
        </group>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube004__0.geometry}
          material={materials['Cube.004__0']}
          position={[0, 140.291, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube006__0.geometry}
          material={materials['Cube.004__0']}
          position={[0, 140.291, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube010_glass_0.geometry}
          material={materials.glass}
          position={[0, 140.291, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube011__0.geometry}
          material={materials['Cube.004__0']}
          position={[0, 140.291, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder004__0.geometry}
          material={materials['Cube.004__0']}
          position={[0, 140.291, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube001_Emission_0.geometry}
          material={materials.Emission}
          position={[0, 140.291, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube002_Emission_0.geometry}
          material={materials.Emission}
          position={[0, 140.291, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/neovector_x-01__futuristic_sci-fi_design/scene.gltf')


rembrandt

city
